### ISSUE TITLE
When no button specified at MousePressEvent, it gets called multiple times`

### ISSUE THREAD

**Issue by WhiteBlackGoose** [asc-community/MxEngine#26]
Reproduction: `~` then click once then observe how many times it got called

**Comment by WhiteBlackGoose** [comment]
Even without clicking it calls the event

**Comment by MomoDeve** [comment]
I agree, `MousePressEvent` should not be triggered if no button is pressed
So I decided to split it into the following events:
`MouseButtonEvent` - generic event that is triggered if **any** mouse button event occured (pressed, released, held)
`LeftMouseButtonPressedEvent`, `RightMouseButtonPressedEvent`, `MiddleMouseButtonPressedEvent` - events for convenience, triggered only on left/right/middle button **press**

**Comment by MomoDeve** [comment]
fixed with commit https://github.com/asc-community/MxEngine/commit/a373555908ea82fb136dfbb8dc1579c33808db02
