### ISSUE TITLE
Проблемы сборки в Visual Studio

### ISSUE THREAD

**Issue by DistinctVision** [asc-community/MxEngine#33]
После сборки по нажатию "Собрать" по CMakeLists.txt появляется папка out, там можно найти либы в папке lib, но экзешников в принципе нигде не появляется.
В окне вывода последние строчки:
`
  Примечание: включение файла:    D:\Projects\MxEngine\samples\SandboxApplication\Gameplay\CubeObject.h
  Примечание: включение файла:    D:\Projects\MxEngine\samples\SandboxApplication\Gameplay\Arc170Object.h
  Примечание: включение файла:    D:\Projects\MxEngine\samples\SandboxApplication\Gameplay\DestroyerObject.h
  Примечание: включение файла:    D:\Projects\MxEngine\samples\SandboxApplication\Gameplay\DeathStarObject.h
  Примечание: включение файла:    D:\Projects\MxEngine\samples\SandboxApplication\Gameplay\SphereObject.h
  Примечание: включение файла:    D:\Projects\MxEngine\samples\SandboxApplication\Gameplay\GridObject.h
  Примечание: включение файла:    D:\Projects\MxEngine\samples\SandboxApplication\Gameplay\SurfaceObject.h
  Примечание: включение файла:    D:\Projects\MxEngine\samples\SandboxApplication\Gameplay\CameraObject.h
  Примечание: включение файла:    D:\Projects\MxEngine\samples\SandboxApplication\Gameplay\Lights.h
  Примечание: включение файла:    D:\Projects\MxEngine\samples\SandboxApplication\Gameplay\SoundObject.h
  Примечание: включение файла:    D:\Projects\MxEngine\samples\SandboxApplication\Gameplay\PBRObject.h
  ninja: build stopped: subcommand failed.
Сбой Сборка.
`
Visual Studio Community 2019

**Comment by MomoDeve** [comment]
exe-шник семпла должен лежать в `MxEngine/out/build/x64-<тип сборки>/samples/<имя семпла>` и копироваться в `MxEngine/samples/<имя семпла>`
Приложите пожалуйста полный лог компиляции, исходя только из этих строк я не могу понять, что именно не работает.
Банальный вопрос: на диске достаточно места?

**Comment by DistinctVision** [comment]
Места хватает. Понимаю что информации маловато. Ошибок компиляции нет, только предупреждения. Лог вывода больше полезной информации не несёт. Есть ещё откуда логи брать? Нашел файлы .ninja_log и build.ninja в папке out.
[ninja_log.txt](https://github.com/asc-community/MxEngine/files/5562795/ninja_log.txt)
[build.ninja.txt](https://github.com/asc-community/MxEngine/files/5562802/build.ninja.txt)
Судя по логу что-то не так с ninja. 
Вполне может быть, что конкретно с моей студией что-то не то.

**Comment by MomoDeve** [comment]
Пробовали перезапустить студию, с нуля собрать проект? (если вы билдили до этого как-то иначе, вполне возможно остались невалидные файлы смейка, лучше все это удалить). По логам ninja ошибок также не видно, пути все вполне валидные

**Comment by DistinctVision** [comment]
Пробовал

**Comment by MomoDeve** [comment]
Чтобы открыть проект, выбираете в главном меню Visual Studio склонированную папку:
![изображение](https://user-images.githubusercontent.com/40578274/99669047-91303180-2a7f-11eb-9baa-fb737c3d0b0a.png)
Убедитесь, что CMake действительно сгенерировал все правильно:
![изображение](https://user-images.githubusercontent.com/40578274/99668588-02bbb000-2a7f-11eb-8c7f-08c709f477a0.png)
Процесс сборки-запуска выглядит так:
![изображение](https://user-images.githubusercontent.com/40578274/99668733-2d0d6d80-2a7f-11eb-93ae-38e78743005d.png)
Этот процесс установки проверялся несколькими людьми, у всех все работало. Если вы повторяете те же шаги, но при этом у вас происходят такого рода ошибки, скорее всего проблема в вашей Visual Studio / OC

**Comment by DistinctVision** [comment]
Сделал все по инструкции, удалив кеш - результат тот же. Хотя тоже самое я и делал до этого. Да, вполне может быть, что проблема с моей версией студии.
