### ISSUE TITLE
Fix a badge (anti-shackaling)

### ISSUE THREAD

**Issue by WhiteBlackGoose** [asc-community/MxEngine#46]
Instead of the travis one you have on readme, I suggest

[![Travis Build Status](https://api.travis-ci.org/asc-community/MxEngine.png?branch=master)](https://travis-ci.org/asc-community/MxEngine) -> [![Travis Build Status](https://img.shields.io/travis/asc-community/MxEngine?logo=travis)](https://travis-ci.org/asc-community/MxEngine)

Code for it:
```
[![Travis Build Status](https://img.shields.io/travis/asc-community/MxEngine?logo=travis)](https://travis-ci.org/asc-community/MxEngine)
```

(I can't open a PR at the moment)

**Comment by WhiteBlackGoose** [comment]
@MomoDeve 🦆

**Comment by MomoDeve** [comment]
done
