### ISSUE TITLE
Build fail on arch-based system

### ISSUE THREAD

**Issue by tree786** [asc-community/MxEngine#56]
Hi

I am using manjaro, and wanted to try and build the project. I git cloned the repo (`git clone --recurse-submodules`), and then ran the `cmake ..` and `make -j` commands, however I get a fail at 64% , with this error: 
```
[ 64%] Building CXX object src/assimp/code/CMakeFiles/assimp.dir/AssetLib/IFC/IFCBoolean.cpp.o
/home/mm/Desktop/MxEngine/submodules/assimp/code/AssetLib/AMF/AMFImporter_Postprocess.cpp: In member function ‘void Assimp::AMFImporter::Postprocess_AddMetadata(const std::__cxx11::list<CAMFImporter_NodeElement_Metadata*>&, aiNode&) const’:
/home/mm/Desktop/MxEngine/submodules/assimp/code/AssetLib/AMF/AMFImporter_Postprocess.cpp:324:55: error: loop variable ‘metadata’ of type ‘const CAMFImporter_NodeElement_Metadata&’ binds to a temporary constructed from type ‘CAMFImporter_NodeElement_Metadata* const’ [-Werror=range-loop-construct]
  324 |         for (const CAMFImporter_NodeElement_Metadata &metadata : metadataList) {
      |                                                       ^~~~~~~~
/home/mm/Desktop/MxEngine/submodules/assimp/code/AssetLib/AMF/AMFImporter_Postprocess.cpp:324:55: note: use non-reference type ‘const CAMFImporter_NodeElement_Metadata’ to make the copy explicit or ‘CAMFImporter_NodeElement_Metadata* const&’ to prevent copying

```
I also get a few more errors (if you want, i can attach the full build log, but it's pretty large).
How do i fix this errors? Is it a dependencies i am missing? If you need any more info from me let me know.

Ahoj

**Comment by MomoDeve** [comment]
https://github.com/assimp/assimp/commit/6ebae5e67c49097b1c55a51f4ead053bc33d8255#diff-8661d947a3e3e62e89e56dc9231cf0090baf8d429ce2d3fadd525dafdea5c4fa
Its assimp build error with gcc11. You can pull changes to assimp submodule and create MR if everything works fine

**Comment by tree786** [comment]
ok i see, no problem then, i close issue
