### ISSUE TITLE
Random::Range() goes out of specified range

### ISSUE THREAD

**Issue by fall2019** [asc-community/MxEngine#57]
@Momo
Hi. The particle system call this function at  GetRandomVector3(ParticleSystem::Shape shape).             
I replace 
int rng = Random::Range(0, 4);
with
std::random_device rd;
std::mt19937 gen(rd()); 
std::uniform_int_distribution<> distr(0, 4);
int rng = distr(gen);
then works fine.
So maybe the function range() should be fixed.

**Comment by fall2019** [comment]
![图片](https://user-images.githubusercontent.com/53587145/187027057-42a71f6d-25f3-4f9b-be52-6d8abe2a1834.png)

**Comment by MomoDeve** [comment]
fixed: https://github.com/asc-community/MxEngine/pull/58
