### ISSUE TITLE
Mechanical Engineering is the ONLY engineering. Period.

### ISSUE THREAD

**Issue by ghost** [asc-community/MxEngine#60]
This post is in response to the disrespectful lie where you misused the respected word "Engineering" in your description section of Mx. 
Hey @MomoDeve  Please stop making lies about real  Engineering. 
Engineering has nothing to do with sitting behind keyboard and writing code. There is no such thing as "software" "engineering". That is the stupidest, most pathetic & disrespectful lie ever. Stop being disrespectful to real engineering (mechanical engineering is the ONLY engineering). Engineering is a real subject. Engineering means designing and building
real mechanical systems, like vehicular engines and turbojets. 
Software dev is easy and has absolutely nothing to do with engineering, they are just being stupid liars. They will never be engineers, not even close. They are just stupid kiddos.

Mechanical Engineering is the ONLY engineering. Period.

**Comment by WhiteBlackGoose** [comment]
Closed as violation of [Code of Conduct](https://github.com/asc-community/.github/blob/main/CODE_OF_CONDUCT.md)
