### ISSUE TITLE
Crashes with invalid pointer when viewport removed

### ISSUE THREAD

**Issue by WhiteBlackGoose** [asc-community/MxEngine#7]
Error reproduction:
1. Run the template project
2. Switch to the Editor mode
3. Go to Render Editor > Camera controller
4. Delete the only viewport
5. Switch back to the Scene mode
6. Wait until some binded events are called

**Comment by MomoDeve** [comment]
forget to check if a camera is valid in InputControl rotate event. Anyway, thanks, fix will be added in v7.0.1
