### ISSUE TITLE
why is the sun shadow like this?

### ISSUE THREAD

**Issue by ghost** [asc-community/MxEngine#85]
![image](https://github.com/asc-community/MxEngine/assets/118131071/17d61671-a920-4a22-ad7d-69ea1530db39)

in every sample the shadow that is casted from the sun looks like this is this normal?

**Comment by MomoDeve** [comment]
You can reduce shadow layer size to improve shadow quality

**Comment by ghost** [comment]
like this?:
`auto& shadowLayer = MxObject::GetByName("ShadowLayer");`

**Comment by MomoDeve** [comment]
Try open it in editor. It's directional light component. You can edit scale of each sascade depth map

**Comment by ghost** [comment]
![image](https://github.com/asc-community/MxEngine/assets/118131071/cc3f7723-e7fc-4859-8467-21036cea9140)
when i change the directional light settings and even after removing and adding a new one i still get wierd shadows but this wierdly only applies to directional light but not to point light

**Comment by MomoDeve** [comment]
I will investigate an issue and update dir light shadows with improved algorithm
