### ISSUE TITLE
why are we still using an ancient version of imgui

### ISSUE THREAD

**Issue by ghost** [asc-community/MxEngine#86]
The current version of ImGui (WIP 1.79) is quite outdated. I attempted to upgrade to the latest version, but encountered problems due to significant changes in the docking API. Initially, I tried upgrading to version 1.83, but even that proved unsuccessful in my attempt to reach the latest version.

**Comment by MomoDeve** [comment]
Yeah, it was not updated for quite a while as it was serving it's purpose without any issues. Thanks for noting, I will update it soon
