### ISSUE TITLE
is there a operation guide?

### ISSUE THREAD

**Issue by qiyuewuyi2333** [asc-community/MxEngine#99]
I have cloned this engine, and built it. It runned as i thought. But I didn't see any imgui components that let me to edit the scene.

I tried the projectTemplated and Sandbox as readme file say. But nothing i can do.

thanks for answer.

**Comment by MomoDeve** [comment]
have you opened console with ` or ~ key?

**Comment by qiyuewuyi2333** [comment]
> have you opened console with ` or ~ key?

ok I got that. thx
